General: 
  nTimesteps: 24 # number of timesteps
  nReprDays: 1 # days
  nDays: 365 # days
  nYears: 1 # years
  # sigmaCM: 0 # CM switch

ADMM:
  rho_EOM: 1 # rho ADMM penalty term, EOM
  rho_CM: 1 # rho ADMM penalty term, CM
  max_iter: 1500
  epsilon: 0.1 # stopping criterion - tolerance on "accuracy" with which the coupling constraints are satisfied. Applied to dual and primal residuals.
  CircularBufferSize: 5 # number of iterations for which data will be retained, should be at least 2 and less than max_iter

EOM: 
  parameter_A: 1 # dummy, not used 


Consumers: # consumers by zones
  A:
    WTP: 5000.0 # Value of lost load (€/MWh) # change the name to WTP
    D: "A" # Demand timeseries that needs to be picked up
    ela: 0.000001 # fraction of demand that is elastic
    sigmaCM: 0

  B:
    WTP: 5000.0 # Value of lost load (€/MWh)
    D: "B" # Timeseries that needs to be picked up
    ela: 0.000001 # fraction of demand that is elastic
    sigmaCM: 0

  C:
    WTP: 5000.0 # Value of lost load (€/MWh)
    D: "C" # Timeseries that needs to be picked up
    ela: 0.000001 # fraction of demand that is elastic
    sigmaCM: 1

Generators: 
  # OPEX are parametrized as a/2 x g^2 + b x g
  A: 
    Baseload:
      a: 0.008 # (€/MWh)^2
      b: 36 # €/MWh
      C: 0 # MW - existing capacity (set to zero if greenfield)
      I: 180000.1 # €/MW-year - annualized investment cost (convert to €/MW-year?)
      max_cap: 50000 # MW - maximum capacity
      sigmaCM: 1

    MidMerit:
      a: 0.032 # (€/MWh)^2
      b: 53 # €/MWh
      C: 0 # MW - existing capacity (set to zero if greenfield)
      I: 100000.1 # €/MW-year - annualized investment cost
      max_cap: 50000 # MW - maximum capacity
      sigmaCM: 1

    Peak:
      a: 0.08 # (€/MWh)^2
      b: 76 # €/MWh
      C: 0 # MW - existing capacity (set to zero if greenfield)
      I: 70000.1 # €/MW-year - annualized investment cost
      max_cap: 100000 # MW - maximum capacity
      sigmaCM: 1

    WindOnshore:
      a: 0 # (€/MWh)^2
      b: 0 # €/MWh
      C: 11706 # MW
      I: 300000 # €/MW-day - annualized investment cost
      max_cap: 11706 # MW - maximum capacity
      AF: "A"
      sigmaCM: 0

    PV:
      a: 0 # (€/MWh)^2
      b: 0 # €/MWh
      C: 27259 # MW
      I: 300000 # €/MW-year - annualized investment cost
      max_cap: 27259 # MW - maximum capacity
      AF: "A"
      sigmaCM: 0

  B:
    Baseload:
      a: 0.008 # (€/MWh)^2
      b: 36 # €/MWh
      C: 0 # MW - existing capacity (set to zero if greenfield)
      I: 180000.05 # €/MW-year - annualized investment cost (convert to €/MW-year?)
      max_cap: 50000 # MW - maximum capacity
      sigmaCM: 1

    MidMerit:
      a: 0.032 # (€/MWh)^2
      b: 53 # €/MWh
      C: 0 # MW - existing capacity (set to zero if greenfield)
      I: 100000.05 # €/MW-year - annualized investment cost
      max_cap: 50000 # MW - maximum capacity
      sigmaCM: 1

    Peak:
      a: 0.08 # (€/MWh)^2
      b: 76 # €/MWh
      C: 0 # MW - existing capacity (set to zero if greenfield)
      I: 70000.05 # €/MW-year - annualized investment cost
      max_cap: 100000 # MW - maximum capacity
      sigmaCM: 1

    WindOnshore:
      a: 0 # (€/MWh)^2
      b: 0 # €/MWh
      C: 5439 # MW
      I: 300000 # €/MW-day - annualized investment cost
      max_cap: 5439 # MW - maximum capacity
      AF: "B"
      sigmaCM: 0

    PV:
      a: 0 # (€/MWh)^2
      b: 0 # €/MWh
      C: 10794 # MW
      I: 300000 # k€/MW-year - annualized investment cost
      max_cap: 10794 # MW - maximum capacity
      AF: "B"
      sigmaCM: 0

  C: 
    Baseload:
      a: 0.008 # (€/MWh)^2
      b: 36 # €/MWh
      C: 0 # MW - existing capacity (set to zero if greenfield)
      I: 180000 # €/MW-year - annualized investment cost (convert to €/MW-year?)
      max_cap: 50000 # MW - maximum capacity
      sigmaCM: 1

    MidMerit:
      a: 0.032 # (€/MWh)^2
      b: 53 # €/MWh
      C: 0 # MW - existing capacity (set to zero if greenfield)
      I: 100000 # €/MW-year - annualized investment cost
      max_cap: 50000 # MW - maximum capacity
      sigmaCM: 1

    Peak:
      a: 0.08 # (€/MWh)^2
      b: 76 # €/MWh
      C: 0 # MW - existing capacity (set to zero if greenfield)
      I: 70000 # €/MW-year - annualized investment cost
      max_cap: 100000 # MW - maximum capacity
      sigmaCM: 1
      
    WindOnshore:
      a: 0 # (€/MWh)^2
      b: 0 # €/MWh
      C: 72618 # MW
      I: 300000 # €/MW-day - annualized investment cost
      max_cap: 72618 # MW - maximum capacity
      AF: "C"
      sigmaCM: 0

    PV:
      a: 0 # (€/MWh)^2
      b: 0 # €/MWh
      C: 86952 # MW
      I: 300000 # k€/MW-year - annualized investment cost
      max_cap: 86952 # MW - maximum capacity
      AF: "C"
      sigmaCM: 0
CM:
  A:
    capacity_target: 20000.0   # MW (capacity demand for zone A)
    price_target: 180000.0    # €/MW-day (price target for zone A)
    capacity_margin: 0.10     # 10% capacity margin
    min_price: -1000000
    max_price: 1000000
  B:
    capacity_target: 20000.0
    price_target: 180000.0
    capacity_margin: 0.10
    min_price: -1000000
    max_price: 1000000
  C:
    capacity_target: 40000.0
    price_target: 180000.0
    capacity_margin: 0.10
    min_price: -1000000
    max_price: 1000000


Network:
  nLines: 4
  nScenarios: 4
  ptdf: "ptdf"  # PTDF dataframe
  np_max: "np_max"
  coupling: "FB"  # or "FB" or "ATC"

  MEC:
    AB: 3000
    BC: 3000
    CA: 3000

  from_zone:
    AB: A
    BC: B
    CA: C

  to_zone:
    AB: B
    BC: C
    CA: A

